name: Student app CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test

  # api-key to git hub: rnd_hwCNcTbOjE4oS6Xm9S9D2NoMnXRW 
  # service-ID: srv-cj1ja8p8g3ne7u77oj4g

  deploy:

    needs: build
  
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID_STUDENT }}
          api-key: ${{ secrets.RENDER_API_STUDENT }}
